export const FETCH_AUTO_COMPLETE_RESULTS = 'FETCH_AUTO_COMPLETE_RESULTS';
export const SET_PREDICTIONS = 'SET_PREDICTIONS';
export const SET_SELECTED_DESTINATION = 'SET_SELECTED_DESTINATION';
export const RESET_PREDICTION = 'RESET_PREDICTION';
export const REMOVE_DESTINATION = 'REMOVE_DESTINATION';
